---
title: "Data Preparation"
author: "Md Zia Uddin Foisal"
date: "2024-Jan-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Remove everything that is in the global enviroment
rm(list=ls())
```

```{r}
#Set the Working Directory
setwd("E:/RDL - Bangladesh Integrated Spatial Database/BGD-Disaster-Climate-Risk-Dashboard-World-Bank/")
```


```{r, echo=FALSE, warning=FALSE}
#Utils
library(readr)
library(dplyr)
library(tidyr)
library(purrr)
library(sf)
library(stringr)
library(glue)
library(janitor)
library(rio)
library(readxl)
#remotes::install_github("wbPTI/devPTIpack")
library(devPTIpack)
library(stringr)
```

##Read the administrative boundaries

```{r}
#District 64 and Upazila 584 BBS
district_shp <- st_read("./CCDR_Dashboard/raw_data/bgd_shp.gpkg", layer = "District")
upazila_shp <- st_read("./CCDR_Dashboard/raw_data/bgd_shp.gpkg", layer = "Upazila")

```

##Preparing the Diaster and Climate Risk Data

```{r}
#Reading Data
#Natural Hazard Data
natural_hazards <- rio::import_list("./CCDR_Dashboard/raw_data/BGD_RSK_23.xlsx")

hazards_district <- natural_hazards[["ADM2_summary"]] %>% 
  as_tibble()%>% 
  rename(division = ADM1_NAME, district = ADM2_NAME) %>% 
  #select(-ADM0_CODE, -ADM0_NAME, -ADM1_CODE, -ADM2_CODE) %>% 
  rename(dist_population = ADM2_POP) %>% 
  mutate(dist_population = dist_population/1000) %>% 
  pivot_longer(dist_population:`DR_S1_50p_mean` ,names_to = "indicator", values_to = "value") %>% 
  mutate(polygon = "District", domain = "Natural Hazards") %>% 
  arrange(district) %>% 
  mutate(value = case_when(
    indicator = str_detect(indicator, "%") ~ value*100,
    TRUE ~ value
  ))%>% 
  clean_names()

hazards_upazila <- natural_hazards[["ADM3_summary"]]%>% 
  as_tibble() %>% 
  #select(-ADM0_CODE, -ADM1_CODE, -ADM2_CODE, -ADM3_CODE, -ADM0_NAME) %>% 
  rename(division = ADM1_NAME , district = ADM2_NAME, upazila = ADM3_NAME) %>%
  rename(upazila_poplation = ADM3_POP) %>% 
  mutate(upazila_poplation = upazila_poplation/1000) %>%
  pivot_longer(upazila_poplation:`DR_S1_50p_mean` ,names_to = "indicator", values_to = "value") %>% 
  mutate(polygon = "Upazila", domain = "Natural Hazards") %>% 
  arrange(upazila) %>% 
  mutate(value = case_when(
    indicator = str_detect(indicator, "%") ~ value*100,
    TRUE ~ value
  )) %>% 
  clean_names()


hazards <- bind_rows(hazards_district, hazards_upazila)

```

##Bringing Relative Wealth Index


```{r}
##Bringing in Relative Wealth Indices at district and Upazila level
rwi_data <- rio::import_list("./CCDR_Dashboard/raw_data/BGD_RWI_Summary.xlsx")

#district rwi 
rwi_district <- rwi_data$ADM2_RWI_Summary %>% 
  pivot_longer(rwi_mean:rwi_majority ,names_to = "indicator", values_to = "value") %>% 
  mutate(polygon = "District", domain = "Relative Wealth Index") %>% 
  arrange(district)

cols.dis <- c("adm1_code", "adm2_code")
rwi_district[cols.dis] <- sapply(rwi_district[cols.dis], as.numeric)


#Upazila rwi
rwi_upazila <- rwi_data$ADM3_RWI_Summary %>% 
  pivot_longer(rwi_mean:rwi_majority ,names_to = "indicator", values_to = "value") %>%
  mutate(polygon = "Upazila", domain = "Relative Wealth Index") %>% 
  arrange(upazila)

cols.upa <- c("adm1_code", "adm2_code", "adm3_code")
rwi_upazila[cols.upa] <- sapply(rwi_upazila[cols.upa], as.numeric)


#rwi_combined
rwi_final <- 
  bind_rows(rwi_district, rwi_upazila)

```


##Preparing the Socio-economic data


```{r}
# #Socio-economic Indicator
development_district <- development_indicators %>% 
  select(adm1_code, adm2_code, division, district, indicator, value) %>% 
  mutate(polygon = "District", domain = "Development Outcomes") %>%
  arrange(district)

```

##Combinning all the dataset

```{r}

dis_and_rwi <- bind_rows(hazards, rwi_final)
district_rwi_disaster <- bind_rows(hazards_district, rwi_district)

#district level data
socio_disaster_rwi_district <- bind_rows(development_district, district_rwi_disaster)

#Combining all data
data_final <- bind_rows(socio_disaster_rwi_district, dis_and_rwi)
```


```{r}
mtdta <- read.csv("./CCDR_Dashboard/raw_data/legend_final_CSV_version.csv")

## Add relevant with the main dataset

data_final$indicator_1 <- mtdta$var_name[match(data_final$indicator , mtdta$var_code)]
data_final$unit <- mtdta$var_units[match(data_final$indicator , mtdta$var_code)]
data_final$source <- mtdta$source [match(data_final$indicator , mtdta$var_code)]
data_final$context <- mtdta$context [match(data_finalindicator , mtdta$var_code)]
data_final$definition <- mtdta$var_description[match(data_final$indicator , mtdta$var_code)]

#write.csv(data_final, "./CCDR_Dashboard/raw_data/data_final.csv", row.names = FALSE)
```

##Writing the dataset as rds

```{r}
write_rds(data_final, file = "./CCDR_Dashboard/data/data.Rds")
```

##Writing the Bangladesh Boundary data in RDS format

```{r}
bgd_shp <- list(District = district_shp, Upazila = upazila_shp)
bgd_shp %>% write_rds("./CCDR_Dashboard/data/bgd_shp.Rds")

```

```{r}
socio_disaster_rwi_district$indicator_1 <- mtdta$var_name[match(socio_disaster_rwi_district$indicator, mtdta$var_code)]
#write.csv(socio_disaster_rwi_district, "./CCDR_Dashboard/raw_data/socio_disaster_rwi_district.csv", row.names = FALSE)

socio_disaster_rwi_district_wide <- socio_disaster_rwi_district %>% 
  select(adm1_code, adm2_code, division, district, indicator_1, value) %>% 
  pivot_wider(id_cols = c("district"), names_from = "indicator_1", values_from = "value", values_fn = list(d = function(x) x[1]))


socio_disaster_rwi_district_wide[is.na(socio_disaster_rwi_district_wide)] <- 0

#write.csv(socio_disaster_rwi_district_wide, "./CCDR_Dashboard/raw_data/socio_disaster_rwi_district_wide_test.csv", row.names = FALSE)


data_pca <- read.csv("./CCDR_Dashboard/raw_data/data_pca_all_3.csv", header = TRUE, sep = ",")
data_pca[is.na(data_pca)] <- 0

#write.csv(data_pca, "./CCDR_Dashboard/raw_data/data_pca_excel_version.csv", row.names = FALSE)

```



```{r}
library(sf)

admin0_Country <- st_read("./CCDR_Dashboard/raw_data/bgd_geometries.gpkg", layer = "admin0_Country")
admin2_District <- st_read("./CCDR_Dashboard/raw_data/bgd_geometries.gpkg", layer = "admin2_District")

district_shp <- st_read("./CCDR_Dashboard/raw_data/bgd_shp.gpkg", layer = "District")
upazila_shp <- st_read("./CCDR_Dashboard/raw_data/bgd_shp.gpkg", layer = "Upazila")
```


```{r}



```





#bgd geometries
```{r}
#Making a List
bgd_geometries <- list(admin0_Country = admin0_Country, admin2_District = admin2_District)

bgd_geometries %>% 
  write_rds("./CCDR_Dashboard/data/bgd_geometries.Rds")

```


##Writing climate meta data
```{r}
###Metadata for PTI
metadata_climate <- import_list("./CCDR_Dashboard/raw_data/bgd_metadata_climate.xlsx")
#devPTIpack::validate_metadata(metadata_climate)

metadata_climate %>% 
  write_rds("./CCDR_Dashboard/data/bgd_metadata_climate.Rds")
```


##Preparing data for PCA

```{r}

data_pca <- metadata_climate$admin2_District
data_pca %>% 
  write_rds("./CCDR_Dashboard/data/data_pca.Rds")

```

#Legend
```{r}
legend_rds <- metadata_climate[["metadata"]]
write_rds(legend_rds, "./CCDR_Dashboard/data/legend.Rds")
```

#district

```{r}
district <- read.csv("./CCDR_Dashboard/raw_data/district.csv")
write_rds(district, "./CCDR_Dashboard/data/districts.Rds")
```

#data

```{r}
data <- read.csv("./CCDR_Dashboard/raw_data/data_final.csv")
write_rds(data, "./CCDR_Dashboard/data/data.Rds")
```


